# Generated by Django 2.1.7 on 2020-08-17 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20200816_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoty',
            field=models.CharField(default=True, max_length=56),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogapp.Post'),
        ),
    ]
