# Generated by Django 2.1.7 on 2020-08-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_auto_20200825_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogapp.Post'),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
